/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Controller.DB_Process;
import Controller.KhachHangDatabase;
import Controller.NhanVienDataBase;
import Model.KhachHang;
import Model.NhanVien;
import java.awt.Color;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ADMIN
 */
public class Admin_Main extends javax.swing.JFrame {

    /**
     * Creates new form Admin_Main
     */
    DefaultTableModel dtm_nhanVien= new DefaultTableModel();
    
    Vector v_header=new Vector<>();
    Vector v_content=new Vector<>();
    ArrayList<NhanVien>List_nv=new ArrayList<>();
    DateFormat df=new SimpleDateFormat("yyyy/MM/dd");
    DB_Process p=new DB_Process();
    NhanVienDataBase nhanVienDataBase=new NhanVienDataBase();
    static String role="";
    public Admin_Main(String role) {
        initComponents();
        this.role=role;
        ButtonGroup group=new ButtonGroup();
        group.add(rdbt_nam);
        group.add(rdbt_nu);
        v_header.add("Mã nhân viên");
        v_header.add("Họ tên");
        v_header.add("Ngày sinh");
        v_header.add("Giới tính");
        v_header.add("Địa chỉ");
        v_header.add("SĐT");
        v_header.add("Chức vụ");
        List_nv=nhanVienDataBase.GetNhanVien();
        for(int i=0;i<List_nv.size();i++){
            Vector<String> v_record=new Vector<>();
            v_record.add(List_nv.get(i).getMaNV());
            v_record.add(List_nv.get(i).getTenNV());
            v_record.add(df.format(List_nv.get(i).getNgaySinh()));
            v_record.add(List_nv.get(i).getGioiTinh());
            v_record.add(List_nv.get(i).getDiaChi());
            v_record.add(List_nv.get(i).getSDT());
            v_record.add(List_nv.get(i).getChucVu());
            v_content.add(v_record);
        }
        dtm_nhanVien.setDataVector(v_content, v_header);
        tb_nhanvien.setModel(dtm_nhanVien);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panel_nhanvien = new javax.swing.JPanel();
        pannel_thongtin_nv = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_tennv = new javax.swing.JTextField();
        txt_ns = new javax.swing.JTextField();
        rdbt_nam = new javax.swing.JRadioButton();
        rdbt_nu = new javax.swing.JRadioButton();
        txt_dc = new javax.swing.JTextField();
        txt_sdt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbb_cv = new javax.swing.JComboBox<String>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_nhanvien = new javax.swing.JTable();
        pannel_chucnang_nv = new javax.swing.JPanel();
        bt_them = new javax.swing.JButton();
        bt_sua = new javax.swing.JButton();
        bt_xoa = new javax.swing.JButton();
        bt_dong = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(MAXIMIZED_BOTH);

        panel_nhanvien.setBackground(new java.awt.Color(0, 255, 204));

        pannel_thongtin_nv.setBackground(new java.awt.Color(0, 255, 204));
        pannel_thongtin_nv.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin nhân viên"));

        jLabel3.setText("Tên:");

        jLabel1.setText("Ngày sinh:");

        jLabel4.setText("Giới tính:");

        jLabel5.setText("Địa chỉ:");

        jLabel6.setText("SĐT:");

        rdbt_nam.setSelected(true);
        rdbt_nam.setText("Nam");

        rdbt_nu.setText("Nữ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("DANH MỤC NHÂN VIÊN");
        jLabel7.setToolTipText("");

        jLabel2.setText("Chức vụ");

        cbb_cv.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nhân viên", "Quản lý" }));

        javax.swing.GroupLayout pannel_thongtin_nvLayout = new javax.swing.GroupLayout(pannel_thongtin_nv);
        pannel_thongtin_nv.setLayout(pannel_thongtin_nvLayout);
        pannel_thongtin_nvLayout.setHorizontalGroup(
            pannel_thongtin_nvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannel_thongtin_nvLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pannel_thongtin_nvLayout.createSequentialGroup()
                .addGroup(pannel_thongtin_nvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pannel_thongtin_nvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pannel_thongtin_nvLayout.createSequentialGroup()
                        .addGroup(pannel_thongtin_nvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_sdt)
                            .addComponent(txt_tennv))
                        .addGap(24, 24, 24))
                    .addGroup(pannel_thongtin_nvLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(rdbt_nam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(119, 119, 119)
                        .addComponent(rdbt_nu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(23, 23, 23)))
                .addGroup(pannel_thongtin_nvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2))
                .addGap(48, 48, 48)
                .addGroup(pannel_thongtin_nvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_ns, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                    .addComponent(txt_dc)
                    .addComponent(cbb_cv, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pannel_thongtin_nvLayout.setVerticalGroup(
            pannel_thongtin_nvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannel_thongtin_nvLayout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pannel_thongtin_nvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_ns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tennv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pannel_thongtin_nvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_dc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txt_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pannel_thongtin_nvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rdbt_nam)
                    .addComponent(rdbt_nu)
                    .addComponent(jLabel2)
                    .addComponent(cbb_cv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tb_nhanvien.setBackground(new java.awt.Color(255, 155, 153));
        tb_nhanvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên", "Tên nhân viên", "Giới tính", "Ngày sinh", "Địa chỉ", "SĐT", "Chức vụ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tb_nhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_nhanvienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_nhanvien);

        pannel_chucnang_nv.setBackground(new java.awt.Color(0, 255, 204));
        pannel_chucnang_nv.setLayout(new java.awt.GridLayout(1, 0, 40, 0));

        bt_them.setBackground(new java.awt.Color(204, 153, 255));
        bt_them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Add.png"))); // NOI18N
        bt_them.setText("Thêm");
        bt_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_themActionPerformed(evt);
            }
        });
        pannel_chucnang_nv.add(bt_them);

        bt_sua.setBackground(new java.awt.Color(204, 153, 255));
        bt_sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Modify.png"))); // NOI18N
        bt_sua.setText("Sửa");
        bt_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_suaActionPerformed(evt);
            }
        });
        pannel_chucnang_nv.add(bt_sua);

        bt_xoa.setBackground(new java.awt.Color(204, 153, 255));
        bt_xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Delete.png"))); // NOI18N
        bt_xoa.setText("Xóa");
        bt_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_xoaActionPerformed(evt);
            }
        });
        pannel_chucnang_nv.add(bt_xoa);

        bt_dong.setBackground(new java.awt.Color(204, 153, 255));
        bt_dong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Back.png"))); // NOI18N
        bt_dong.setText("Trở về");
        bt_dong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_dongActionPerformed(evt);
            }
        });
        pannel_chucnang_nv.add(bt_dong);

        javax.swing.GroupLayout panel_nhanvienLayout = new javax.swing.GroupLayout(panel_nhanvien);
        panel_nhanvien.setLayout(panel_nhanvienLayout);
        panel_nhanvienLayout.setHorizontalGroup(
            panel_nhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_nhanvienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_nhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pannel_chucnang_nv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pannel_thongtin_nv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel_nhanvienLayout.setVerticalGroup(
            panel_nhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_nhanvienLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(pannel_thongtin_nv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addGap(25, 25, 25)
                .addComponent(pannel_chucnang_nv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jTabbedPane1.addTab("Nhân Viên", panel_nhanvien);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_dongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_dongActionPerformed
        // TODO add your handling code here:
            ChucNang_Main chucNang_Main=new ChucNang_Main("Quản lý");
            chucNang_Main.show();
            this.dispose();
        
    }//GEN-LAST:event_bt_dongActionPerformed

    private void bt_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_xoaActionPerformed
        // TODO add your handling code here:
       
        
        if(tb_nhanvien.getSelectedRow()>=0){
            int index=tb_nhanvien.getSelectedRow();
            if(nhanVienDataBase.DeleteNhanVien(List_nv.get(index).getMaNV())){
                dtm_nhanVien.removeRow(index);
                List_nv.remove(index);
            }
            else{
                int n=JOptionPane.showConfirmDialog(this, "Nhân viên đang làm việc không thể xóa!!!",
                    "Thông báo",JOptionPane.CLOSED_OPTION,1);
            }
            
        }
        else{
            int n=JOptionPane.showConfirmDialog(this, "Vui lòng chọn nhân viên !!!",
                    "Thông báo",JOptionPane.CLOSED_OPTION,1);
        }
    }//GEN-LAST:event_bt_xoaActionPerformed

    private void bt_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_suaActionPerformed
        // TODO add your handling code here:
       
        if(tb_nhanvien.getSelectedRow()>=0){
           int index=tb_nhanvien.getSelectedRow();
            

            try {
                NhanVien nv=new NhanVien(String.valueOf(tb_nhanvien.getValueAt(index, 0)),
                        txt_tennv.getText(),rdbt_nam.isSelected()?"Nam":"Nữ",
                    df.parse(txt_ns.getText()),txt_dc.getText(),txt_sdt.getText(),String.valueOf(cbb_cv.getSelectedItem()));
                if(p.isSDT(txt_sdt.getText())){
                    Date d=new Date();
                    if(isValidDate(txt_ns.getText())&&df.parse(txt_ns.getText()).compareTo(d)<0){
                        if(nhanVienDataBase.UpdateNhanVien(nv)){
                            List_nv.set(index, nv);
                            dtm_nhanVien.setValueAt(txt_tennv.getText(), index, 1);
                            dtm_nhanVien.setValueAt(txt_ns.getText(), index, 2);
                            dtm_nhanVien.setValueAt(rdbt_nam.isSelected()?"Nam":"Nữ", index, 3);
                            dtm_nhanVien.setValueAt(txt_dc.getText(), index, 4);
                            dtm_nhanVien.setValueAt(txt_sdt.getText(), index, 5);
                            dtm_nhanVien.setValueAt(String.valueOf(cbb_cv.getSelectedItem()), index, 6);
                        }
                        else{
                            int n=JOptionPane.showConfirmDialog(this, "SDT của nhân viên đã tồn tại!!!",
                            "Thông báo",JOptionPane.CLOSED_OPTION,1);
                        }
                    }
                    else{
                        int n=JOptionPane.showConfirmDialog(this, "Vui lòng nhập đúng ngày sinh theo định dạng yyyy/mm/dd!!!",
                        "   Thông báo",JOptionPane.CLOSED_OPTION,1);
                    }
                }
                else{
                    int n=JOptionPane.showConfirmDialog(this, "Vui lòng nhập đúng SDT!!!",
                            "Thông báo",JOptionPane.CLOSED_OPTION,1);
                }
               
            } catch (Exception e) {
                int n=JOptionPane.showConfirmDialog(this, "Vui lòng nhập đúng ngày sinh theo định dạng yyyy/mm/dd!!!",
                    "Thông báo",JOptionPane.CLOSED_OPTION,1);
            }

        }
        else{
            int n=JOptionPane.showConfirmDialog(this, "Vui lòng chọn nhân viên !!!",
                    "Thông báo",JOptionPane.CLOSED_OPTION,1);
        }
    }//GEN-LAST:event_bt_suaActionPerformed

    boolean isValidDate(String input) {
        df.setLenient(false); // set false để kiểm tra tính hợp lệ của date. VD: tháng 2 phải có 28-29 ngày, năm có 12 tháng,....
        try {
            df.parse(input); // parse dateString thành kiểu Date
        }
        catch (ParseException e) { // quăng lỗi nếu dateString ko hợp lệ
            return false;
        }
        return true;
    }
    private void bt_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_themActionPerformed
        // TODO add your handling code here:

        if(txt_tennv.getText().equals("")&&txt_dc.getText().equals("")&&txt_ns.getText().equals("")&&txt_sdt.getText().equals("")){
            int n=JOptionPane.showConfirmDialog(this, "Vui lòng nhập đủ thông tin nhân viên!!!","Thông báo",JOptionPane.CLOSED_OPTION,1);
        }
        else{
            if(txt_tennv.getText().equals("")){
                int n=JOptionPane.showConfirmDialog(this, "Vui lòng nhập họ tên nhân viên!!!","Thông báo",JOptionPane.CLOSED_OPTION,1);
            }
            else if(txt_ns.getText().equals("")){
                int n=JOptionPane.showConfirmDialog(this, "Vui lòng nhập ngày sinh nhân viên!!!","Thông báo",JOptionPane.CLOSED_OPTION,1);
            }
            else if(txt_dc.getText().equals("")){
                int n=JOptionPane.showConfirmDialog(this, "Vui lòng nhập địa chỉ nhân viên!!!","Thông báo",JOptionPane.CLOSED_OPTION,1);
            }
            else if(txt_sdt.getText().equals("")){
                int n=JOptionPane.showConfirmDialog(this, "Vui lòng nhập số điện thoaị nhân viên!!!","Thông báo",JOptionPane.CLOSED_OPTION,1);
            }
            else if(!p.isSDT(txt_sdt.getText())){
                int n=JOptionPane.showConfirmDialog(this, "Vui lòng nhập đúng số điện thoaị nhân viên!!!","Thông báo",JOptionPane.CLOSED_OPTION,1);
            }
            else{
                try {
                    
                    
                    Vector<String> v_record=new Vector<>();
                    String id="TCLKT"+p.getID(List_nv.size(),nhanVienDataBase.v_ID_NV(List_nv));
                    if(p.isSDT(txt_sdt.getText())){
                        Date d=new Date();
                        NhanVien nv=new NhanVien(id, txt_tennv.getText(), rdbt_nam.isSelected()?"Nam":"Nữ",
                        df.parse(txt_ns.getText()), txt_dc.getText(),txt_sdt.getText(),String.valueOf(cbb_cv.getSelectedItem()));
                        if(isValidDate(txt_ns.getText())&&df.parse(txt_ns.getText()).compareTo(d)<0){
                            if(nhanVienDataBase.InsertNhanVien(nv)){      
                                List_nv.add(nv);
                                v_record.add(nv.getMaNV());
                                v_record.add(nv.getTenNV());
                                v_record.add(df.format(nv.getNgaySinh()));
                                v_record.add(nv.getGioiTinh());
                                v_record.add(nv.getDiaChi());
                                v_record.add(nv.getSDT());
                                v_record.add(nv.getChucVu());
                                v_content.add(v_record);
                                List_nv.add(nv);
                                dtm_nhanVien.setDataVector(v_content, v_header);
                        }
                        else{
                            int n=JOptionPane.showConfirmDialog(this, "SDT của nhân viên đã tồn tại!!!",
                            "Thông báo",JOptionPane.CLOSED_OPTION,1);
                        }
                    }
                    else{
                        int n=JOptionPane.showConfirmDialog(this, "Vui lòng nhập đúng ngày sinh theo định dạng yyyy/mm/dd!!!",
                        "Thông báo",JOptionPane.CLOSED_OPTION,1);
                    } 
                    }
                    else{
                         int n=JOptionPane.showConfirmDialog(this, "Vui lòng nhập đúng SDT!!!",
                            "Thông báo",JOptionPane.CLOSED_OPTION,1);
                    }
                    
                } catch (Exception e) {
                    int n=JOptionPane.showConfirmDialog(this, "Vui lòng nhập đúng ngày sinh theo định dạng yyyy/mm/dd!!!",
                        "Thông báo",JOptionPane.CLOSED_OPTION,1);
                }
            }

        }
    }//GEN-LAST:event_bt_themActionPerformed

    private void tb_nhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_nhanvienMouseClicked
        // TODO add your handling code here:
       
        if(tb_nhanvien.getSelectedRow()>=0){

            int index=tb_nhanvien.getSelectedRow();

            txt_tennv.setText(List_nv.get(index).getTenNV());
            txt_ns.setText(df.format(List_nv.get(index).getNgaySinh()));
            if(List_nv.get(index).getGioiTinh().equals("Nam")){
                rdbt_nam.setSelected(true);
            }
            else{
                rdbt_nu.setSelected(true);
            }
            txt_dc.setText(List_nv.get(index).getDiaChi());
            txt_sdt.setText(List_nv.get(index).getSDT());
        }
        

    }//GEN-LAST:event_tb_nhanvienMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Main(role).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_dong;
    private javax.swing.JButton bt_sua;
    private javax.swing.JButton bt_them;
    private javax.swing.JButton bt_xoa;
    private javax.swing.JComboBox<String> cbb_cv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel panel_nhanvien;
    private javax.swing.JPanel pannel_chucnang_nv;
    private javax.swing.JPanel pannel_thongtin_nv;
    private javax.swing.JRadioButton rdbt_nam;
    private javax.swing.JRadioButton rdbt_nu;
    private javax.swing.JTable tb_nhanvien;
    private javax.swing.JTextField txt_dc;
    private javax.swing.JTextField txt_ns;
    private javax.swing.JTextField txt_sdt;
    private javax.swing.JTextField txt_tennv;
    // End of variables declaration//GEN-END:variables
}
