/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author ADMIN
 */
public class ThongKe_User_main extends javax.swing.JFrame {

    /**
     * Creates new form ThongKe_User
     */
    static String role="";
    public ThongKe_User_main(String role) {
        initComponents();
        this.role=role;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        bt_hd = new javax.swing.JButton();
        bt_mh = new javax.swing.JButton();
        bt_kh = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bt_troVe = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(MAXIMIZED_BOTH);
        getContentPane().setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(102, 255, 102));

        jPanel3.setBackground(new java.awt.Color(51, 255, 51));
        jPanel3.setLayout(new java.awt.GridLayout(3, 0, 0, 30));

        bt_hd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt_hd.setText("Hóa đơn");
        bt_hd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hdActionPerformed(evt);
            }
        });
        jPanel3.add(bt_hd);

        bt_mh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt_mh.setText("Mặt hàng");
        bt_mh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_mhActionPerformed(evt);
            }
        });
        jPanel3.add(bt_mh);

        bt_kh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt_kh.setText("Khách hàng");
        bt_kh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_khActionPerformed(evt);
            }
        });
        jPanel3.add(bt_kh);

        jPanel4.setBackground(new java.awt.Color(51, 255, 51));
        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THỐNG KÊ CỬA HÀNG");
        jPanel4.add(jLabel1);

        bt_troVe.setBackground(new java.awt.Color(153, 153, 255));
        bt_troVe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Back.png"))); // NOI18N
        bt_troVe.setText("Trở về");
        bt_troVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_troVeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1043, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_troVe, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                .addGap(40, 40, 40)
                .addComponent(bt_troVe)
                .addGap(40, 40, 40))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_hdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hdActionPerformed
        ThongKe_HD tkhd=new ThongKe_HD(role);
        tkhd.show();
        this.dispose();
    }//GEN-LAST:event_bt_hdActionPerformed

    private void bt_mhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_mhActionPerformed
        // TODO add your handling code here:
        ThongKe_Hang tkh=new ThongKe_Hang(role);
        tkh.show();
        this.dispose();
    }//GEN-LAST:event_bt_mhActionPerformed

    private void bt_khActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_khActionPerformed
        // TODO add your handling code here:
        ThongKe_KH tkkh=new ThongKe_KH(role);
        tkkh.show();
        this.dispose();
    }//GEN-LAST:event_bt_khActionPerformed

    private void bt_troVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_troVeActionPerformed
        ChucNang_Main cnm=new ChucNang_Main(role);
        cnm.show();
        this.dispose();
    }//GEN-LAST:event_bt_troVeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongKe_User_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongKe_User_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongKe_User_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongKe_User_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongKe_User_main(role).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_hd;
    private javax.swing.JButton bt_kh;
    private javax.swing.JButton bt_mh;
    private javax.swing.JButton bt_troVe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
