/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.DB_Connection;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class TimKiem_HD extends javax.swing.JFrame {

    /**
     * Creates new form TimKiem_HD
     */
    static String role;
    DefaultTableModel dtm=new DefaultTableModel();
    Vector v_header=new  Vector();
    Vector v_content=new  Vector();
    DateFormat df=new SimpleDateFormat("yyyy/MM/dd");
    public Date addDaysToJavaUtilDate(Date date, int hours) {
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(date);
        calendar.add(Calendar.DAY_OF_MONTH, hours);
        return calendar.getTime();
    }
    public TimKiem_HD(String role) {
        this.role=role;
        initComponents();
         this.getContentPane().setBackground(new Color(51,255,255));
        v_header.add("Mã hóa đơn");
        v_header.add("Mã nhân viên");
        v_header.add("Tên nhân viên");
        v_header.add("Mã khách ");
        v_header.add("Ngày bán");
        v_header.add("Tổng tiền");
        dtm.setDataVector(v_content, v_header);
        jTable2.setModel(dtm);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txt_ngay1 = new javax.swing.JTextField();
        txt_ngay2 = new javax.swing.JTextField();
        rdbt_Ngay = new javax.swing.JRadioButton();
        rdbt_tennv = new javax.swing.JRadioButton();
        txt_tennv = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 255));
        setExtendedState(MAXIMIZED_BOTH);

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16))); // NOI18N

        buttonGroup1.add(rdbt_Ngay);
        rdbt_Ngay.setSelected(true);
        rdbt_Ngay.setText("Ngày");
        rdbt_Ngay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbt_NgayActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbt_tennv);
        rdbt_tennv.setText("Tên nhân viên");
        rdbt_tennv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbt_tennvActionPerformed(evt);
            }
        });

        txt_tennv.setEnabled(false);
        txt_tennv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tennvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rdbt_Ngay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rdbt_tennv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_tennv, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(txt_ngay1))
                .addGap(104, 104, 104)
                .addComponent(txt_ngay2, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ngay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ngay2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdbt_Ngay))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbt_tennv)
                    .addComponent(txt_tennv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(51, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setBackground(new java.awt.Color(51, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TÌM KIẾM HÓA ĐƠN");
        jPanel2.add(jLabel1);

        jTable2.setBackground(new java.awt.Color(255, 155, 153));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jButton1.setBackground(new java.awt.Color(204, 153, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Search.png"))); // NOI18N
        jButton1.setText("Tìm kiếm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        jButton2.setBackground(new java.awt.Color(204, 153, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Back.png"))); // NOI18N
        jButton2.setText("Trờ về");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        TimKiem_user_main tk=new TimKiem_user_main(role);
        tk.show();
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    
    SimpleDateFormat format = new SimpleDateFormat("yyyy/MM/dd");
    boolean isValidDate(String input) {
        df.setLenient(false); // set false để kiểm tra tính hợp lệ của date. VD: tháng 2 phải có 28-29 ngày, năm có 12 tháng,....
        try {
            df.parse(input); // parse dateString thành kiểu Date
        }
        catch (ParseException e) { // quăng lỗi nếu dateString ko hợp lệ
            return false;
        }
        return true;
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
        
        if(rdbt_Ngay.isSelected()){
            v_content.removeAllElements();
            txt_tennv.setText("");
            if(txt_ngay1.getText().equals("")||txt_ngay2.getText().equals("")){
                int n=JOptionPane.showConfirmDialog(this, "Vui lòng nhập  ngày !!!",
                        "Thông báo",JOptionPane.CLOSED_OPTION,1);
            }
            else{
                
                if(isValidDate(txt_ngay1.getText())&&isValidDate(txt_ngay2.getText())){
                    Connection cn= DB_Connection.getCon();
                    String sql=String.format("exec sp_TimKiem_HoaDon_TheoNgay '%s','%s'", 
                    txt_ngay1.getText(),txt_ngay2.getText());
                    try {  
                        PreparedStatement ps=(PreparedStatement)cn.prepareCall(sql);
                        ResultSet rs=ps.executeQuery();
                        while(rs.next()){
                            Vector<String> v_record=new Vector<>();
                            v_record.add(rs.getString("MaHD"));
                            v_record.add(rs.getString("MaNV"));
                            v_record.add(rs.getString("TenNV"));
                            v_record.add(rs.getString("MaKhach"));
                            Date date=addDaysToJavaUtilDate(rs.getDate("NgayBan"), 0);
                            v_record.add(df.format(date));
                            v_record.add(String.valueOf(rs.getInt("TongTien")));
                            v_content.add(v_record);
                        }
                        if(v_content.isEmpty()){
                            int n=JOptionPane.showConfirmDialog(this, "Không có hóa đơn !!!",
                        "Thông báo",JOptionPane.CLOSED_OPTION,1);
                        }
                        cn.close();
                        dtm.setDataVector(v_content, v_header);
                    } catch (Exception e) {
                    }
                }
                else{
                    int n=JOptionPane.showConfirmDialog(this, "Vui lòng nhập đúng ngày theo định dạng yyyy/mm/dd!!!",
                        "Thông báo",JOptionPane.CLOSED_OPTION,1);
                }
            }
            
        }
        else if(rdbt_tennv.isSelected()){
            v_content.removeAllElements();
            if(txt_tennv.getText().equals("")){
                int n=JOptionPane.showConfirmDialog(this, "Vui lòng nhập tên nhân viên!!!",
                        "Thông báo",JOptionPane.CLOSED_OPTION,1);
            }
            else{
                Connection cn= DB_Connection.getCon();
                String sql=String.format("exec sp_TimKiem_HoaDon_TenNV N'%s'", 
                    txt_tennv.getText());
                try {
               
                    PreparedStatement ps=(PreparedStatement)cn.prepareCall(sql);
                    ResultSet rs=ps.executeQuery();
                    while(rs.next()){
                        Vector<String> v_record=new Vector<>();
                        v_record.add(rs.getString("MaHD"));
                        v_record.add(rs.getString("MaNV"));
                        v_record.add(rs.getString("TenNV"));
                        v_record.add(rs.getString("MaKhach"));
                        Date date=addDaysToJavaUtilDate(rs.getDate("NgayBan"), 0);
                        v_record.add(df.format(date));
                        v_record.add(String.valueOf(rs.getInt("TongTien")));
                        v_content.add(v_record);
               
                    }
                    if(v_content.isEmpty()){
                            int n=JOptionPane.showConfirmDialog(this, "Không có hóa đơn !!!",
                        "Thông báo",JOptionPane.CLOSED_OPTION,1);
                    }
                    cn.close();
                    dtm.setDataVector(v_content, v_header);
       
                } catch (Exception e) {
                }
            }
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rdbt_tennvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbt_tennvActionPerformed
        // TODO add your handling code here:
        v_content.removeAllElements();
         dtm.setDataVector(v_content, v_header);
        txt_ngay1.setEnabled(false);
        txt_ngay2.setEnabled(false);
        txt_tennv.setEnabled(true);
        txt_ngay1.setText("");
        txt_ngay2.setText("");
        txt_tennv.setText("");
    }//GEN-LAST:event_rdbt_tennvActionPerformed

    private void rdbt_NgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbt_NgayActionPerformed
        // TODO add your handling code here:
        
        v_content.removeAllElements(); 
         dtm.setDataVector(v_content, v_header);
        txt_tennv.setEnabled(false);
        txt_ngay1.setEnabled(true);
        txt_ngay2.setEnabled(true);
        txt_ngay1.setText("");
        txt_ngay2.setText("");
        txt_tennv.setText("");
    }//GEN-LAST:event_rdbt_NgayActionPerformed

    private void txt_tennvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tennvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tennvActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TimKiem_HD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TimKiem_HD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TimKiem_HD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TimKiem_HD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TimKiem_HD(role).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JRadioButton rdbt_Ngay;
    private javax.swing.JRadioButton rdbt_tennv;
    private javax.swing.JTextField txt_ngay1;
    private javax.swing.JTextField txt_ngay2;
    private javax.swing.JTextField txt_tennv;
    // End of variables declaration//GEN-END:variables
}
