/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.DB_Connection;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Vector;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class Timkiem_admin_main extends javax.swing.JFrame {

    /**
     * Creates new form Timkiem_admin_main
     */
    
    DefaultTableModel dtm=new DefaultTableModel();
    Vector v_content=new Vector();
    Vector v_header=new Vector();
    static String role="";
    public Timkiem_admin_main(String role) {
        initComponents();
        this.role=role;
         this.getContentPane().setBackground(new Color(51,255,255));
        v_header.add("Mã nhân viên");
        v_header.add("Tên nhân viên"); 
        v_header.add("Giới tính");
        v_header.add("Ngày sinh");
        v_header.add("Địa chỉ");
        v_header.add("SDT");
        dtm.setDataVector( v_content,v_header);
        tb_nhanvien.setModel(dtm);
        txt_qq.setText("");
        txt_ht.setEnabled(true);
        txt_qq.setEnabled(false);
        buttonGroup1.clearSelection();
        rdbt_nam.setEnabled(false);
        rdbt_nu.setEnabled(false);
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rdbt_nu = new javax.swing.JRadioButton();
        rdbt_nam = new javax.swing.JRadioButton();
        txt_ht = new javax.swing.JTextField();
        txt_qq = new javax.swing.JTextField();
        cb_ht = new javax.swing.JRadioButton();
        cb_gt = new javax.swing.JRadioButton();
        cb_qq = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_nhanvien = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        bt_tk = new javax.swing.JButton();
        bt_trove = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(MAXIMIZED_BOTH);

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin nhân viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16))); // NOI18N

        buttonGroup1.add(rdbt_nu);
        rdbt_nu.setText("Nữ");

        buttonGroup1.add(rdbt_nam);
        rdbt_nam.setText("Nam");

        txt_ht.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_htActionPerformed(evt);
            }
        });

        buttonGroup2.add(cb_ht);
        cb_ht.setSelected(true);
        cb_ht.setText("Họ Tên");
        cb_ht.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_htActionPerformed(evt);
            }
        });

        buttonGroup2.add(cb_gt);
        cb_gt.setText("Giới tính");
        cb_gt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_gtActionPerformed(evt);
            }
        });

        buttonGroup2.add(cb_qq);
        cb_qq.setText("Quê quán");
        cb_qq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_qqActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_ht)
                    .addComponent(cb_gt)
                    .addComponent(cb_qq))
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_qq)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rdbt_nam, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                        .addGap(147, 147, 147)
                        .addComponent(rdbt_nu, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                        .addGap(290, 290, 290))
                    .addComponent(txt_ht))
                .addGap(100, 100, 100))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ht, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_ht))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbt_nam)
                    .addComponent(rdbt_nu)
                    .addComponent(cb_gt))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_qq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_qq))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(51, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TÌM KIẾM NHÂN VIÊN");
        jPanel2.add(jLabel1);

        tb_nhanvien.setBackground(new java.awt.Color(255, 155, 153));
        tb_nhanvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb_nhanvien);

        jPanel3.setBackground(new java.awt.Color(51, 255, 255));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        bt_tk.setBackground(new java.awt.Color(204, 153, 255));
        bt_tk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Search.png"))); // NOI18N
        bt_tk.setText("Tìm kiếm");
        bt_tk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tkActionPerformed(evt);
            }
        });
        jPanel3.add(bt_tk);

        bt_trove.setBackground(new java.awt.Color(204, 153, 255));
        bt_trove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Back.png"))); // NOI18N
        bt_trove.setText("Trờ về");
        bt_trove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_troveActionPerformed(evt);
            }
        });
        jPanel3.add(bt_trove);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 959, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(275, 275, 275)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addGap(67, 67, 67)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public Date addDaysToJavaUtilDate(Date date, int hours) {
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(date);
        calendar.add(Calendar.DAY_OF_MONTH, hours);
        return calendar.getTime();
    }  
    DateFormat df=new SimpleDateFormat("yyyy/MM/dd");
    private void bt_tkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tkActionPerformed
        // TODO add your handling code here:
       
        
        if(cb_ht.isSelected()){
            v_content.removeAllElements();
            if(txt_ht.getText().equals("")){
                 int n=JOptionPane.showConfirmDialog(this, "Vui lòng nhập tên nhân viên!!!",
                        "Thông báo",JOptionPane.CLOSED_OPTION,1);
            }
            else{
                Connection cn=DB_Connection.getCon();
                try {
                    String sql=String.format("exec sp_TimKiem_NhanVien_HT N'%s'", txt_ht.getText());
                    PreparedStatement ps=(PreparedStatement)cn.prepareStatement(sql);
                    ResultSet rs=ps.executeQuery();
                    while(rs.next()){
                        Vector<String> v_recored=new Vector<>();
                        v_recored.add(rs.getString("MaNV"));
                        v_recored.add(rs.getString("TenNV"));
                        v_recored.add(rs.getString("GioiTinh"));
                        Date date=addDaysToJavaUtilDate(rs.getDate("NgaySinh"), 0);
                        v_recored.add(df.format(date));
                        v_recored.add(rs.getString("DiaChi"));
                        v_recored.add(rs.getString("SDT"));
                        v_content.add(v_recored);
                    }
                    dtm.setDataVector(v_content,v_header);
                    if(v_content.isEmpty()){
                            int n=JOptionPane.showConfirmDialog(this, "Không có nhân viên !!!",
                        "Thông báo",JOptionPane.CLOSED_OPTION,1);
                        }
                
                } catch (Exception e) {
                }
            }
            
        
        }
        else if(cb_gt.isSelected()){
            v_content.removeAllElements();
            Connection cn=DB_Connection.getCon();
            String GT=rdbt_nam.isSelected()?"Nam":"Nữ";
            try {
                String sql=String.format("exec sp_TimKiem_NhanVien_GioiTinh N'%s'",GT);
                PreparedStatement ps=(PreparedStatement)cn.prepareStatement(sql);
                ResultSet rs=ps.executeQuery();
                while(rs.next()){
                    Vector<String> v_recored=new Vector<>();
                    v_recored.add(rs.getString("MaNV"));
                    v_recored.add(rs.getString("TenNV"));
                    v_recored.add(rs.getString("GioiTinh"));
                    Date date=addDaysToJavaUtilDate(rs.getDate("NgaySinh"), 0);
                    v_recored.add(df.format(date));
                    v_recored.add(rs.getString("DiaChi"));
                    v_recored.add(rs.getString("SDT"));
                    v_content.add(v_recored);
                }
                dtm.setDataVector(v_content,v_header);
                if(v_content.isEmpty()){
                            int n=JOptionPane.showConfirmDialog(this, "Không có nhân viên !!!",
                        "Thông báo",JOptionPane.CLOSED_OPTION,1);
                        }
                
            } catch (Exception e) {
            }
            
            
        }
        else if(cb_qq.isSelected()){
            v_content.removeAllElements();
            if(txt_qq.getText().equals("")){
                 int n=JOptionPane.showConfirmDialog(this, "Vui lòng nhập quê quán!!!",
                        "Thông báo",JOptionPane.CLOSED_OPTION,1);
            }
            else{
                Connection cn=DB_Connection.getCon();
                String QQ=txt_qq.getText();
                try {
                    String sql=String.format("exec sp_TimKiem_NhanVien_QQ N'%s'",QQ);
                    PreparedStatement ps=(PreparedStatement)cn.prepareStatement(sql);
                    ResultSet rs=ps.executeQuery();
                    while(rs.next()){
                        Vector<String> v_recored=new Vector<>();
                        v_recored.add(rs.getString("MaNV"));
                        v_recored.add(rs.getString("TenNV"));
                        v_recored.add(rs.getString("GioiTinh"));
                        Date date=addDaysToJavaUtilDate(rs.getDate("NgaySinh"), 0);
                        v_recored.add(df.format(date));
                        v_recored.add(rs.getString("DiaChi"));
                        v_recored.add(rs.getString("SDT"));
                        v_content.add(v_recored);
                    }
                    dtm.setDataVector(v_content,v_header);
                    if(v_content.isEmpty()){
                            int n=JOptionPane.showConfirmDialog(this, "Không có nhân viên !!!",
                        "Thông báo",JOptionPane.CLOSED_OPTION,1);
                        }
                
                } catch (Exception e) {
                }
            }
            
            
        }
    }//GEN-LAST:event_bt_tkActionPerformed

    private void bt_troveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_troveActionPerformed
        // TODO add your handling code here:
        ChucNang_Main cnm=new ChucNang_Main(role);
        cnm.show();
        this.dispose();
    }//GEN-LAST:event_bt_troveActionPerformed

    private void cb_htActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_htActionPerformed
        // TODO add your handling code here:
        v_content.removeAllElements();
         dtm.setDataVector(v_content, v_header);
        txt_qq.setText("");
        txt_ht.setText("");
        txt_ht.setEnabled(true);
        txt_qq.setEnabled(false);
        buttonGroup1.clearSelection();
        rdbt_nam.setEnabled(false);
        rdbt_nu.setEnabled(false);
        
        
    }//GEN-LAST:event_cb_htActionPerformed

    private void cb_qqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_qqActionPerformed
        // TODO add your handling code here:
        v_content.removeAllElements();
         dtm.setDataVector(v_content, v_header);
        txt_ht.setText("");
        txt_qq.setText("");
        txt_ht.setEnabled(false);
        txt_qq.setEnabled(true);
        buttonGroup1.clearSelection();
        rdbt_nam.setEnabled(false);
        rdbt_nu.setEnabled(false);
        
        
    }//GEN-LAST:event_cb_qqActionPerformed

    private void cb_gtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_gtActionPerformed
        // TODO add your handling code here:
         v_content.removeAllElements();
          dtm.setDataVector(v_content, v_header);
         rdbt_nam.setSelected(true);
         rdbt_nam.setEnabled(true);
         rdbt_nu.setEnabled(true);
         txt_ht.setText("");
         txt_ht.setEnabled(false);
         txt_qq.setText("");
         txt_qq.setEnabled(false);
    }//GEN-LAST:event_cb_gtActionPerformed

    private void txt_htActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_htActionPerformed
        // TODO add your handling code here:
        v_content.removeAllElements();
         dtm.setDataVector(v_content, v_header);
        txt_ht.setText("");
        txt_qq.setText("");
        txt_ht.setEnabled(false);
        txt_qq.setEnabled(true);
        buttonGroup1.clearSelection();
        rdbt_nam.setEnabled(false);
        rdbt_nu.setEnabled(false);
    }//GEN-LAST:event_txt_htActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Timkiem_admin_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Timkiem_admin_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Timkiem_admin_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Timkiem_admin_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Timkiem_admin_main(role).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_tk;
    private javax.swing.JButton bt_trove;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton cb_gt;
    private javax.swing.JRadioButton cb_ht;
    private javax.swing.JRadioButton cb_qq;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdbt_nam;
    private javax.swing.JRadioButton rdbt_nu;
    private javax.swing.JTable tb_nhanvien;
    private javax.swing.JTextField txt_ht;
    private javax.swing.JTextField txt_qq;
    // End of variables declaration//GEN-END:variables
}
