/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.DB_Connection;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class TimKiem_Hang extends javax.swing.JFrame {

    /**
     * Creates new form TimKiem_Hang
     */
    static String role;
    DefaultTableModel dtm=new DefaultTableModel();
    Vector v_header=new  Vector();
    Vector v_content=new  Vector();
    DateFormat df=new SimpleDateFormat("yyyy/MM/dd");
    public Date addDaysToJavaUtilDate(Date date, int hours) {
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(date);
        calendar.add(Calendar.DAY_OF_MONTH, hours);
        return calendar.getTime();
    }
    public TimKiem_Hang(String role) {
        this.role=role;
        initComponents();
         this.getContentPane().setBackground(new Color(51,255,255));
        v_header.add("Mã hàng");
        v_header.add("Tên hàng");
        v_header.add("Tên hãng sản xuất");
        v_header.add("Số lượng tồn"); 
        v_header.add("Đơn giá nhập");
        v_header.add("Đơn giá bán");
        v_header.add("Ngày nhập");
        dtm.setDataVector(v_content, v_header);
        jTable1.setModel(dtm);
          
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txt_hsx = new javax.swing.JTextField();
        rbdt_ngayNhap = new javax.swing.JRadioButton();
        rdbt_tenhsx = new javax.swing.JRadioButton();
        txt_ngayNhap = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(MAXIMIZED_BOTH);

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TÌM KIẾM HÀNG");
        jPanel1.add(jLabel1);

        jPanel2.setBackground(new java.awt.Color(51, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16))); // NOI18N

        txt_hsx.setEnabled(false);

        buttonGroup1.add(rbdt_ngayNhap);
        rbdt_ngayNhap.setSelected(true);
        rbdt_ngayNhap.setText("Ngày nhập");
        rbdt_ngayNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbdt_ngayNhapActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbt_tenhsx);
        rdbt_tenhsx.setText("Tên hãng sản xuất");
        rdbt_tenhsx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbt_tenhsxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rdbt_tenhsx, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbdt_ngayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(160, 160, 160)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_ngayNhap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                    .addComponent(txt_hsx, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(190, 190, 190))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbdt_ngayNhap)
                    .addComponent(txt_ngayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbt_tenhsx)
                    .addComponent(txt_hsx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTable1.setBackground(new java.awt.Color(255, 155, 153));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel3.setBackground(new java.awt.Color(51, 255, 255));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jButton1.setBackground(new java.awt.Color(204, 153, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Search.png"))); // NOI18N
        jButton1.setText("Tìm kiếm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        jButton2.setBackground(new java.awt.Color(204, 153, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Back.png"))); // NOI18N
        jButton2.setText("Trở về");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                .addGap(20, 20, 20)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        TimKiem_user_main tk=new TimKiem_user_main(role);
        tk.show();
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    SimpleDateFormat format = new SimpleDateFormat("yyyy/MM/dd");
    boolean isValidDate(String input) {
        df.setLenient(false); // set false để kiểm tra tính hợp lệ của date. VD: tháng 2 phải có 28-29 ngày, năm có 12 tháng,....
        try {
            df.parse(input); // parse dateString thành kiểu Date
        }
        catch (ParseException e) { // quăng lỗi nếu dateString ko hợp lệ
            return false;
        }
        return true;
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
        if(rbdt_ngayNhap.isSelected()){
            v_content.removeAllElements();
            if(txt_ngayNhap.getText().equals("")){
                int n=JOptionPane.showConfirmDialog(this, "Vui lòng nhập ngày !!!",
                        "Thông báo",JOptionPane.CLOSED_OPTION,1);
            }
            else{
                if(isValidDate(txt_ngayNhap.getText())){
                    Connection cn= DB_Connection.getCon();
                    String sql=String.format("exec sp_TimKiem_Hang_NgayNhap '%s'", 
                        txt_ngayNhap.getText());
                    try {
                        PreparedStatement ps=(PreparedStatement)cn.prepareCall(sql);
                        ResultSet rs=ps.executeQuery();
                        while(rs.next()){
                        Vector<String> v_record=new Vector<>();
                        v_record.add(rs.getString("MaHang"));
                        v_record.add(rs.getString("TenHang"));
                        v_record.add(rs.getString("TenHangSanXuat"));
                        v_record.add(String.valueOf(rs.getInt("SoLuongTon")));
                        v_record.add(String.valueOf(rs.getInt("DonGiaNhap")));
                        v_record.add(String.valueOf(rs.getInt("DonGiaBan")));
                        Date date=addDaysToJavaUtilDate(rs.getDate("NgayNhapHang"), 0);
                        v_record.add(df.format(date));
                        v_content.add(v_record);
                
                    }
                    cn.close();
                    if(v_content.isEmpty()){
                            int n=JOptionPane.showConfirmDialog(this, "Không có mặt hàng !!!",
                        "Thông báo",JOptionPane.CLOSED_OPTION,1);
                        }
                    dtm.setDataVector(v_content, v_header);
       
                    } catch (Exception e) {
                    }
                }
                else{
                    int n=JOptionPane.showConfirmDialog(this, "Vui lòng nhập đúng ngày theo định dạng yyyy/mm/dd!!!",
                        "Thông báo",JOptionPane.CLOSED_OPTION,1);
                }
            }
            
        }
        else if(rdbt_tenhsx.isSelected()){
            v_content.removeAllElements();
            if(txt_hsx.getText().equals("")){
                int n=JOptionPane.showConfirmDialog(this, "Vui lòng nhập tên hãng sản xuất!!!",
                        "Thông báo",JOptionPane.CLOSED_OPTION,1);
            }
            else{
                Connection cn= DB_Connection.getCon();
                String sql=String.format("exec sp_TimKiem_Hang_TenHangSX N'%s'", 
                    txt_hsx.getText());
                try {
                    PreparedStatement ps=(PreparedStatement)cn.prepareCall(sql);
                    ResultSet rs=ps.executeQuery();
                    while(rs.next()){
                        Vector<String> v_record=new Vector<>();
                        v_record.add(rs.getString("MaHang"));
                        v_record.add(rs.getString("TenHang"));
                        v_record.add(rs.getString("TenHangSanXuat"));
                        v_record.add(String.valueOf(rs.getInt("SoLuongTon")));
                        v_record.add(String.valueOf(rs.getInt("DonGiaNhap")));
                        v_record.add(String.valueOf(rs.getInt("DonGiaBan")));
                        Date date=addDaysToJavaUtilDate(rs.getDate("NgayNhapHang"), 0);
                        v_record.add(df.format(date));
                        v_content.add(v_record);
                
                    }
                    cn.close();
                    if(v_content.isEmpty()){
                            int n=JOptionPane.showConfirmDialog(this, "Không có hóa đơn !!!",
                        "Thông báo",JOptionPane.CLOSED_OPTION,1);
                        }
                    dtm.setDataVector(v_content, v_header);
       
                } catch (Exception e) {
                }
            }
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rbdt_ngayNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbdt_ngayNhapActionPerformed
        // TODO add your handling code here:
        v_content.removeAllElements();
         dtm.setDataVector(v_content, v_header);
        txt_ngayNhap.setText("");
        txt_hsx.setText("");
        txt_hsx.setEnabled(false);
        txt_ngayNhap.setEnabled(true);
    }//GEN-LAST:event_rbdt_ngayNhapActionPerformed

    private void rdbt_tenhsxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbt_tenhsxActionPerformed
        // TODO add your handling code here:
        v_content.removeAllElements();
         dtm.setDataVector(v_content, v_header);
        txt_ngayNhap.setText("");
        txt_hsx.setText("");
        txt_hsx.setEnabled(true);
        txt_ngayNhap.setEnabled(false);
    }//GEN-LAST:event_rdbt_tenhsxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TimKiem_Hang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TimKiem_Hang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TimKiem_Hang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TimKiem_Hang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TimKiem_Hang(role).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rbdt_ngayNhap;
    private javax.swing.JRadioButton rdbt_tenhsx;
    private javax.swing.JTextField txt_hsx;
    private javax.swing.JTextField txt_ngayNhap;
    // End of variables declaration//GEN-END:variables
}
