/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.DB_Connection;
import Controller.DB_Process;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class TimKiem_KH extends javax.swing.JFrame {

    /**
     * Creates new form TimKiem_KH
     */
    DefaultTableModel dtm=new DefaultTableModel();
    Vector v_header=new Vector<>() ;
    Vector v_content=new Vector();
    static String role;
    public TimKiem_KH(String role) {
        this.role=role;
        initComponents();
         this.getContentPane().setBackground(new Color(51,255,255));
        v_header.add("Mã khách");
        v_header.add("Tên khách");
        v_header.add("Giới tính");
        v_header.add("Địa chỉ");
        v_header.add("SDT");
        
        dtm.setDataVector(v_content,v_header);
        tb_kh.setModel(dtm);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txt_sdt = new javax.swing.JTextField();
        txt_ht = new javax.swing.JTextField();
        rdbt_tkh = new javax.swing.JRadioButton();
        rdbt_sdt = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_kh = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(MAXIMIZED_BOTH);

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TÌM KIẾM KHÁCH HÀNG");
        jPanel1.add(jLabel1);

        jPanel2.setBackground(new java.awt.Color(51, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16))); // NOI18N

        txt_sdt.setEnabled(false);

        buttonGroup1.add(rdbt_tkh);
        rdbt_tkh.setSelected(true);
        rdbt_tkh.setText("Tên khách hàng");
        rdbt_tkh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbt_tkhActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbt_sdt);
        rdbt_sdt.setText("SDT");
        rdbt_sdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbt_sdtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbt_tkh)
                    .addComponent(rdbt_sdt))
                .addGap(160, 160, 160)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_ht, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                    .addComponent(txt_sdt))
                .addGap(180, 180, 180))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ht, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdbt_tkh))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdbt_sdt))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        tb_kh.setBackground(new java.awt.Color(255, 155, 153));
        tb_kh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb_kh);

        jPanel3.setBackground(new java.awt.Color(51, 255, 255));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jButton1.setBackground(new java.awt.Color(255, 153, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Search.png"))); // NOI18N
        jButton1.setText("Tìm kiếm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        jButton2.setBackground(new java.awt.Color(255, 153, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Back.png"))); // NOI18N
        jButton2.setText("Trở về");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
        if(rdbt_sdt.isSelected()){
            v_content.removeAllElements();
            if(txt_sdt.getText().equals("")){
                int n=JOptionPane.showConfirmDialog(this, "Vui lòng nhập SDT!!!",
                        "Thông báo",JOptionPane.CLOSED_OPTION,1);
            }
            else{
                DB_Process p=new DB_Process();
                if(p.isSDT(txt_sdt.getText())){
                    Connection cn=DB_Connection.getCon();
                    String sql=String.format("exec sp_TimKiem_KhachHang_SDT N'%s'",txt_sdt.getText());
                    try {
                        PreparedStatement ps=(PreparedStatement)cn.prepareCall(sql);
                        ResultSet rs=ps.executeQuery();
                    while(rs.next()){
                        Vector<String> v_record=new Vector<>();
                        v_record.add(rs.getString("MaKhach"));
                        v_record.add(rs.getString("TenKhach"));
                        v_record.add(rs.getString("GioiTinh"));
                        v_record.add(rs.getString("DiaChi"));
                        v_record.add(rs.getString("SDT"));
                        v_content.add(v_record);
                    }
                    cn.close();
                    dtm.setDataVector(v_content, v_header);
                    if(v_content.isEmpty()){
                            int n=JOptionPane.showConfirmDialog(this, "Không có khách hàng !!!",
                        "Thông báo",JOptionPane.CLOSED_OPTION,1);
                        }
                    
           
                    } catch (Exception e) {
                    }
                }
                else{
                    int n=JOptionPane.showConfirmDialog(this, "Vui lòng nhập đúng SDT!!!",
                        "Thông báo",JOptionPane.CLOSED_OPTION,1);
                }
            }
            
        }
        if(rdbt_tkh.isSelected()){
            v_content.removeAllElements();
            if(txt_ht.getText().equals("")){
                int n=JOptionPane.showConfirmDialog(this, "Vui lòng nhập tên khách hàng!!!",
                        "Thông báo",JOptionPane.CLOSED_OPTION,1);
            }
            else{
                Connection cn=DB_Connection.getCon();
                String sql=String.format("exec sp_TimKiem_KhachHang_TenKH N'%s'", txt_ht.getText());
                try {
                    PreparedStatement ps=(PreparedStatement)cn.prepareCall(sql);
                    ResultSet rs=ps.executeQuery();
                    while(rs.next()){
                        Vector<String> v_record=new Vector<>();
                        v_record.add(rs.getString("MaKhach"));
                        v_record.add(rs.getString("TenKhach"));
                        v_record.add(rs.getString("GioiTinh"));
                        v_record.add(rs.getString("DiaChi"));
                        v_record.add(rs.getString("SDT"));
                        v_content.add(v_record);
                    }
                    cn.close();
                    if(v_content.isEmpty()){
                            int n=JOptionPane.showConfirmDialog(this, "Không có khách hàng !!!",
                        "Thông báo",JOptionPane.CLOSED_OPTION,1);
                        }
                    dtm.setDataVector(v_content, v_header);
           
                } catch (Exception e) {
                }
            }
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        TimKiem_user_main tk=new TimKiem_user_main(role);
        tk.show();
        this.dispose();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void rdbt_tkhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbt_tkhActionPerformed
        // TODO add your handling code here:
        v_content.removeAllElements();
         dtm.setDataVector(v_content, v_header);
        txt_sdt.setText("");
        txt_ht.setText("");
        txt_ht.setEnabled(true);
        txt_sdt.setEnabled(false);
    }//GEN-LAST:event_rdbt_tkhActionPerformed

    private void rdbt_sdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbt_sdtActionPerformed
        // TODO add your handling code here:
        v_content.removeAllElements();
         dtm.setDataVector(v_content, v_header);
        txt_ht.setText("");
        txt_sdt.setText("");
        txt_ht.setEnabled(false);
        txt_sdt.setEnabled(true);
    }//GEN-LAST:event_rdbt_sdtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TimKiem_KH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TimKiem_KH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TimKiem_KH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TimKiem_KH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TimKiem_KH(role).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdbt_sdt;
    private javax.swing.JRadioButton rdbt_tkh;
    private javax.swing.JTable tb_kh;
    private javax.swing.JTextField txt_ht;
    private javax.swing.JTextField txt_sdt;
    // End of variables declaration//GEN-END:variables
}
